project:
  type: website
  output-dir: docs

website:
  title: "IntroR_Course_LDC"
  navbar:
    right:
      - href: index.qmd
        text: Overview
      - about.qmd
      
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



